source 'https://rubygems.org'

gem 'nanoc', '~> 4.2', '>= 4.2.3'
gem 'adsf'
gem 'rubocop'
#gem 'systemu'
gem 'org-ruby'
gem 'guard-nanoc'
gem 'terminal-notifier'
gem 'terminal-notifier-guard'
gem 'nokogiri', '~> 1.6', '>= 1.6.8'
